insert into student (name, birth_date, address, gender) values ('Gwynne Cosans', '1984-11-10', '5 Scott Park', 'Female');
insert into student (name, birth_date, address, gender) values ('Rosemarie Lefeuvre', '1991-12-29', '40 Loomis Place', 'Female');
insert into student (name, birth_date, address, gender) values ('Sutherlan Shard', '1988-03-01', '3 Dahle Point', 'Male');
insert into student (name, birth_date, address, gender) values ('Whitney Parsall', '1993-10-28', '450 Wayridge Junction', 'Male');
insert into student (name, birth_date, address, gender) values ('Juieta Ambler', '1981-08-30', '1944 Laurel Lane', 'Female');
insert into student (name, birth_date, address, gender) values ('Wren Shovlar', '2019-07-02', '2539 Warbler Parkway', 'Female');
insert into student (name, birth_date, address, gender) values ('Boone Twydell', '2010-02-23', '7 Macpherson Circle', 'Male');
insert into student (name, birth_date, address, gender) values ('Phyllys Chevis', '1999-09-05', '4 Westend Point', 'Female');
insert into student (name, birth_date, address, gender) values ('Ophelie Bossingham', '2012-04-18', '2097 Farwell Plaza', 'Female');
insert into student (name, birth_date, address, gender) values ('Renault Petegrew', '2015-11-21', '51610 Pankratz Parkway', 'Male');
insert into student (name, birth_date, address, gender) values ('Cam Biaggelli', '1987-09-13', '7 Barnett Lane', 'Female');
insert into student (name, birth_date, address, gender) values ('Angelique Gilhooley', '1988-07-08', '1442 Sunfield Alley', 'Female');
insert into student (name, birth_date, address, gender) values ('Marylee McCahey', '2005-06-29', '3 Spohn Junction', 'Female');
insert into student (name, birth_date, address, gender) values ('Dyann Ladbrooke', '2001-03-04', '6 Miller Parkway', 'Female');
insert into student (name, birth_date, address, gender) values ('Filide Clausewitz', '2008-03-14', '36 Kim Court', 'Female');
insert into student (name, birth_date, address, gender) values ('Skelly McHarry', '1985-07-25', '00 Commercial Way', 'Male');
insert into student (name, birth_date, address, gender) values ('Katti Blinckhorne', '1997-11-28', '120 Golf Avenue', 'Female');
insert into student (name, birth_date, address, gender) values ('Earlie Moreno', '1988-07-21', '7 Portage Street', 'Male');
insert into student (name, birth_date, address, gender) values ('Gary Wands', '1982-12-29', '97 Towne Parkway', 'Male');
insert into student (name, birth_date, address, gender) values ('Eugenius Allgood', '2011-12-24', '72119 Comanche Road', 'Male');
insert into student (name, birth_date, address, gender) values ('Elvin Sinkins', '2018-01-03', '05734 Mariners Cove Park', 'Male');
insert into student (name, birth_date, address, gender) values ('Marcos Delacote', '1997-01-07', '00 Lakeland Hill', 'Male');
insert into student (name, birth_date, address, gender) values ('Mohammed Targe', '1994-06-07', '0 Crowley Avenue', 'Male');
insert into student (name, birth_date, address, gender) values ('Olenolin Ogdahl', '1993-05-19', '81 Stuart Hill', 'Male');
insert into student (name, birth_date, address, gender) values ('Gert Vinnick', '1984-10-27', '73 Duke Way', 'Female');
insert into student (name, birth_date, address, gender) values ('Tadeas Egginton', '2001-05-12', '65 2nd Court', 'Male');
insert into student (name, birth_date, address, gender) values ('Stevie Bulloch', '2006-08-20', '916 Reindahl Avenue', 'Male');
insert into student (name, birth_date, address, gender) values ('Nickie Champkin', '2008-10-25', '78928 Charing Cross Parkway', 'Male');
insert into student (name, birth_date, address, gender) values ('Gerhard Andre', '2015-03-27', '8 Del Mar Drive', 'Male');
insert into student (name, birth_date, address, gender) values ('Titos Cortes', '2003-12-19', '2531 Shoshone Terrace', 'Male');
insert into student (name, birth_date, address, gender) values ('Ali Walburn', '1991-07-03', '6454 Hudson Hill', 'Male');
insert into student (name, birth_date, address, gender) values ('Vale Toppas', '1995-02-02', '24860 Marcy Lane', 'Male');
insert into student (name, birth_date, address, gender) values ('Lorrayne Bree', '1997-03-04', '5522 Muir Drive', 'Female');
insert into student (name, birth_date, address, gender) values ('Willabella Thaxton', '2002-09-16', '1663 Pankratz Crossing', 'Female');
insert into student (name, birth_date, address, gender) values ('Holly-anne Hamm', '1994-03-20', '37789 Hermina Way', 'Female');
insert into student (name, birth_date, address, gender) values ('Yorke Barrowcliffe', '1992-06-29', '6 Stephen Trail', 'Male');
insert into student (name, birth_date, address, gender) values ('Dillon Esposita', '1994-04-11', '5155 Onsgard Pass', 'Male');
insert into student (name, birth_date, address, gender) values ('Kathrine Raoux', '2007-05-08', '9 Debra Court', 'Female');
insert into student (name, birth_date, address, gender) values ('Rubin Pedler', '1998-03-20', '8899 Miller Junction', 'Male');
insert into student (name, birth_date, address, gender) values ('Ashien Fearick', '1984-12-26', '2948 Doe Crossing Alley', 'Female');
insert into student (name, birth_date, address, gender) values ('Benedikt Orrill', '1984-11-16', '74264 Northview Way', 'Male');
insert into student (name, birth_date, address, gender) values ('Alida Caunce', '2012-02-06', '8045 Alpine Parkway', 'Female');
insert into student (name, birth_date, address, gender) values ('Samson Janatka', '2015-09-07', '8659 Kingsford Court', 'Male');
insert into student (name, birth_date, address, gender) values ('Clemens Areles', '1995-03-25', '545 Acker Terrace', 'Male');
insert into student (name, birth_date, address, gender) values ('Nickola Stagge', '1986-11-24', '8 Stuart Alley', 'Male');
insert into student (name, birth_date, address, gender) values ('Dane Coltart', '2013-04-23', '3 Ridgeview Alley', 'Male');
insert into student (name, birth_date, address, gender) values ('Stewart Kays', '2007-02-19', '4348 Everett Park', 'Male');
insert into student (name, birth_date, address, gender) values ('Thomasa Kerton', '1989-10-06', '691 Brickson Park Way', 'Female');
insert into student (name, birth_date, address, gender) values ('Sandra Cartman', '2010-11-02', '315 Orin Plaza', 'Female');
insert into student (name, birth_date, address, gender) values ('Angeli McEneny', '1982-09-17', '80 Stoughton Center', 'Male');
insert into student (name, birth_date, address, gender) values ('Cam Sweating', '2011-07-14', '82747 Bultman Park', 'Female');
insert into student (name, birth_date, address, gender) values ('Skye Dhillon', '2014-09-19', '9 Oakridge Parkway', 'Male');
insert into student (name, birth_date, address, gender) values ('Ansell Pickover', '2018-07-25', '2807 Scofield Trail', 'Male');
insert into student (name, birth_date, address, gender) values ('Patricio Lymbourne', '2015-07-04', '850 Maryland Hill', 'Male');
insert into student (name, birth_date, address, gender) values ('Loise Gero', '2004-01-27', '75 Del Sol Park', 'Female');
insert into student (name, birth_date, address, gender) values ('Kiley Bellamy', '2004-04-09', '75 Doe Crossing Drive', 'Male');
insert into student (name, birth_date, address, gender) values ('Rad Spiaggia', '2016-12-19', '2223 Red Cloud Circle', 'Male');
insert into student (name, birth_date, address, gender) values ('Nanon Wontner', '2018-03-08', '639 Hooker Place', 'Female');
insert into student (name, birth_date, address, gender) values ('Rochette Zold', '2011-08-25', '143 Michigan Point', 'Female');
insert into student (name, birth_date, address, gender) values ('Ulrick Mullender', '1994-11-21', '41630 Victoria Drive', 'Male');
insert into student (name, birth_date, address, gender) values ('Kristen Banghe', '1983-10-12', '863 Warrior Plaza', 'Female');
insert into student (name, birth_date, address, gender) values ('Ofella Skokoe', '2015-07-09', '7 Namekagon Crossing', 'Female');
insert into student (name, birth_date, address, gender) values ('Demetrius Verzey', '2010-11-17', '37725 Pond Place', 'Male');
insert into student (name, birth_date, address, gender) values ('Beauregard De Lascy', '2004-05-02', '56 Birchwood Terrace', 'Male');
insert into student (name, birth_date, address, gender) values ('Leisha McMichell', '1988-06-01', '2660 Springs Terrace', 'Female');
insert into student (name, birth_date, address, gender) values ('Gaspar Isley', '2004-11-11', '1 Ohio Road', 'Male');
insert into student (name, birth_date, address, gender) values ('Stephi Byas', '2018-07-12', '106 Debs Court', 'Female');
insert into student (name, birth_date, address, gender) values ('Sigismund Van Dijk', '1991-07-29', '286 Spaight Hill', 'Male');
insert into student (name, birth_date, address, gender) values ('Daryl Yeats', '1993-10-21', '1 Union Avenue', 'Female');
insert into student (name, birth_date, address, gender) values ('Lemuel Rignoldes', '1982-10-26', '89253 Lukken Parkway', 'Male');
insert into student (name, birth_date, address, gender) values ('Chelsae Ramsted', '2009-10-16', '514 Sommers Terrace', 'Female');
insert into student (name, birth_date, address, gender) values ('Philip Joontjes', '1998-02-13', '4433 Gerald Avenue', 'Male');
insert into student (name, birth_date, address, gender) values ('Rick Goroni', '2018-03-03', '2 Chinook Trail', 'Male');
insert into student (name, birth_date, address, gender) values ('Giralda Cheltnam', '1999-09-25', '231 Golden Leaf Junction', 'Female');
insert into student (name, birth_date, address, gender) values ('Dawn Plaschke', '2015-09-21', '0295 Linden Drive', 'Female');
insert into student (name, birth_date, address, gender) values ('Dacie Brewett', '2013-09-02', '4 Rigney Street', 'Female');
insert into student (name, birth_date, address, gender) values ('Tanney Gerber', '1980-10-17', '6985 Hauk Court', 'Male');
insert into student (name, birth_date, address, gender) values ('Jory Aveson', '2019-08-02', '8 Harper Place', 'Male');
insert into student (name, birth_date, address, gender) values ('Odey Irce', '2016-08-26', '1 Debra Street', 'Male');
insert into student (name, birth_date, address, gender) values ('Alex Mapp', '1996-08-05', '4 Sachs Crossing', 'Male');
insert into student (name, birth_date, address, gender) values ('Grady Cavaney', '2005-12-02', '7 Mayfield Lane', 'Male');
insert into student (name, birth_date, address, gender) values ('Berkeley Goosey', '2001-08-09', '1 Dottie Hill', 'Male');
insert into student (name, birth_date, address, gender) values ('Amos Peepall', '2014-03-21', '227 Sommers Place', 'Male');
insert into student (name, birth_date, address, gender) values ('Mikey Bricksey', '1984-11-22', '51922 Toban Crossing', 'Male');
insert into student (name, birth_date, address, gender) values ('Jeff Northwood', '1993-04-24', '979 Reinke Lane', 'Male');
insert into student (name, birth_date, address, gender) values ('Mavis Bertenshaw', '1981-09-28', '387 Calypso Plaza', 'Female');
insert into student (name, birth_date, address, gender) values ('Dehlia Neles', '1985-11-13', '526 Caliangt Plaza', 'Female');
insert into student (name, birth_date, address, gender) values ('Gilbert Colten', '1982-11-13', '853 Columbus Court', 'Male');
insert into student (name, birth_date, address, gender) values ('Karolina Heeran', '1989-09-10', '73713 Westerfield Point', 'Female');
insert into student (name, birth_date, address, gender) values ('Sybille Inkles', '2002-03-05', '30 Cherokee Street', 'Female');
insert into student (name, birth_date, address, gender) values ('Hadrian Acreman', '2011-10-14', '6 Susan Point', 'Male');
insert into student (name, birth_date, address, gender) values ('Annabel Churching', '2019-08-16', '13 Cambridge Pass', 'Female');
insert into student (name, birth_date, address, gender) values ('Loralyn Lomasna', '1997-05-06', '6049 Hazelcrest Terrace', 'Female');
insert into student (name, birth_date, address, gender) values ('Vere Thorius', '1982-02-23', '0 Jenna Street', 'Female');
insert into student (name, birth_date, address, gender) values ('Alvera Craighead', '2011-09-06', '964 Raven Place', 'Female');
insert into student (name, birth_date, address, gender) values ('Vaughn Smithin', '2018-12-15', '77224 Sommers Lane', 'Male');
insert into student (name, birth_date, address, gender) values ('Filbert Tregiddo', '2007-10-25', '46 Lyons Pass', 'Male');
insert into student (name, birth_date, address, gender) values ('Sim Gilburt', '2004-10-12', '25294 Burning Wood Road', 'Male');
insert into student (name, birth_date, address, gender) values ('Addi Burds', '2015-06-30', '8 Nobel Drive', 'Female');
insert into student (name, birth_date, address, gender) values ('Wiatt Pickvance', '1996-08-03', '44822 Union Avenue', 'Male');